global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]

  - job_name: "coshub-api"
    static_configs:
      - targets: ["api:3001"]
    metrics_path: "/api/metrics"
    scrape_interval: 30s

  - job_name: "coshub-web"
    static_configs:
      - targets: ["web:3000"]
    metrics_path: "/api/metrics"
    scrape_interval: 30s

  - job_name: "postgres"
    static_configs:
      - targets: ["postgres:5432"]
    metrics_path: "/metrics"
    scrape_interval: 60s

  - job_name: "redis"
    static_configs:
      - targets: ["redis:6379"]
    metrics_path: "/metrics"
    scrape_interval: 60s

  - job_name: "minio"
    static_configs:
      - targets: ["minio:9000"]
    metrics_path: "/minio/v2/metrics/cluster"
    scrape_interval: 60s
