server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets:
          - localhost
        labels:
          job: varlogs
          __path__: /var/log/*log

  - job_name: containers
    static_configs:
      - targets:
          - localhost
        labels:
          job: containerlogs
          __path__: /var/lib/docker/containers/*/*log

  - job_name: coshub-api
    static_configs:
      - targets:
          - localhost
        labels:
          job: coshub-api
          __path__: /var/log/coshub-api/*.log

  - job_name: coshub-web
    static_configs:
      - targets:
          - localhost
        labels:
          job: coshub-web
          __path__: /var/log/coshub-web/*.log

pipeline_stages:
  - json:
      expressions:
        timestamp: timestamp
        level: level
        message: message
        requestId: requestId
        userId: userId
        method: method
        url: url
        duration: duration
        errorCode: errorCode
        errorMessage: errorMessage

  - timestamp:
      source: timestamp
      format: RFC3339Nano

  - labels:
      level:
      requestId:
      userId:
      method:
      url:
      errorCode:
